# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PocketPlant' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PocketPlant
  pod 'SwiftLint'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Crashlytics'
  
  pod 'Kingfisher'

  pod 'IQKeyboardManagerSwift'
  pod 'Charts'
  pod 'lottie-ios'
  
  target 'PocketPlantTests' do
          inherit! :search_paths
          pod 'SwiftLint'
          pod 'Firebase/Firestore'
          pod 'FirebaseFirestoreSwift'
          pod 'Firebase/Storage'
          pod 'Firebase/Database'
          pod 'Firebase/Auth'
          pod 'Firebase/Crashlytics'
          pod 'Kingfisher'
          pod 'IQKeyboardManagerSwift'
          pod 'Charts'
          pod 'lottie-ios'
  end

end
